baseURL = "http://example.org/"
languageCode = "en-us"
title = "Alpha Church"
theme = ["../.."]

enableEmoji = true
customCSS = ["", ""]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level theme.
#Use the weight= to specify the order of menu items, and the parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "about"
    weight = 2

  [[menu.main]]
    name = "About Us"
    parent = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Leaders"
    parent = "About"
    url = "/leaders"
    weight = 2

  [[menu.main]]
    name = "Resources"
    url = "#"
    weight = 3

  [[menu.main]]
    name = "Sermons"
    url = "/sermons"
    parent = "Resources"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    parent = "Resources"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Paramaters for the whole site
[params]
  title = "Alpha Church"
  subtitle = "Another Church Theme"
  author = "Daniel Saunders"

  bible_popups = true

  [params.podcast]
    title = "Listen to Alpha Church"
    subtitle = ""
    summary = "Alpha-Church sermons, talks, messages—podcasted."
    email = "test@example.com"
    copyright = "Podcast: [CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)"
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"

  [params.map]
    # For Open Street Map widgets
    latitude = "48.8530"
    longitude = "2.3498"
    zoom = "18"

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "netlify"
    confirm_page = "/contact_thanks"
    # formspree_email=""

  #Paramaters for the home/landing page
  [params.landing]

    [params.landing.banner]
      image = "img/banner.jpg"

      [[params.landing.banner.button]]
        url = "/contact"
        text = "Get in touch"
        type = "special"

        [[params.landing.banner.button]]
        url = "#feature-icons"
        text = "Find out more"

    #Details for the box below the banner
    [params.landing.services]
      title = "Church on Sunday"
      text = "We meet at 5 am and 2 pm at [6 Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris](https://www.openstreetmap.org/way/201611261)."
      map_location = "Cathédrale Notre-Dame de Paris"

    [params.landing.feature_icons]
      #These feature icons look best if there's an even number of them.
      enable = true

      #Accent is a colour defined in the CSS file. Choose between 1 and 5
      [[params.landing.feature_icons.tile]]
        icon = "fa-hands-helping"
        icon_pack = "fas"
        accent = "1"
        title = "Serve"
        text = "Growing people who serve our community."

      [[params.landing.feature_icons.tile]]
        icon = "fa-users"
        icon_pack = "fas"
        accent = "2"
        title = "Meet"
        text = "Meeting together to hear."

      [[params.landing.feature_icons.tile]]
        icon = "fa-comments"
        icon_pack = "fas"
        accent = "5"
        title = "Speak"
        text = "Speaking encouragement to one-another."

      [[params.landing.feature_icons.tile]]
        icon = "fa-heartbeat"
        icon_pack = "fas"
        accent = "3"
        title = "Loved"
        text = "Knowing Love. Being Loved."

    [params.landing.feature_images]
      #These feature images look best if there's an even number of them.
      enable = true

      [[params.landing.feature_images.tile]]
        image = "img/freely-10057.jpg"
        title = "Childrens' Ministry"
        text = "A church for the family."
        url = "/kids"
        button_text = "Learn more"

      [[params.landing.feature_images.tile]]
        image = "img/freely-26905.jpg"
        title = "Midweek Ministries"
        text = "Want more during the week?"
        url = "#"
        button_text="Join a group today!"

    [params.landing.CTA]
      heading = "Get in touch!"
      message = "We'd love to hear from you."

    [params.footer]
      copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

    [[params.links]]
      service = "Twitter"
      icon = "fa-twitter"
      icon_pack = "fab"
      link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/"

    [[params.links]]
      service = "Podcast"
      icon = "fa-podcast"
      icon_pack = "fas"
      link = "/sermons/index.xml"

    [[params.links]]
      service = "Full RSS Feed"
      icon = "fa-rss"
      icon_pack = "fas"
      link = "/index.xml"
