baseURL = "http://example.org/"
languageCode = "en-us"
title = "Alpha Church"
theme = "alpha-church"
themesDir = "../.."

rssLimit = 5
paginate = 4

enableEmoji = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

enableInlineShortcodes = true

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

  [[menu.main]]
    name = "About Us"
    parent = "About"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Leaders"
    parent = "About"
    url = "/leaders"
    weight = 2

  [[menu.main]]
    name = "Resources"
    url = "#"
    weight = 3

  [[menu.main]]
    name = "Sermons"
    url = "/sermons"
    parent = "Resources"
    weight = 1

  [[menu.main]]
    name = "Preachers"
    url = "/preachers"
    parent = "Sermons"
    weight = 1

  [[menu.main]]
    name = "Best Ever"
    url = "#"
    parent = "Sermons"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    parent = "Resources"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Paramaters for the whole site
[params]
  title = "Alpha Church"
  subtitle = "Another Church Theme"
  author = "Daniel Saunders"
  keywords = ["theme", "hugo", "podcast"]
  languageCode = "en" # For accessibility this needs to be set. You can find all language codes at https://www.w3schools.com/tags/ref_language_codes.asp
  bible_popups = "faithlife" #faithlife, blb
  bible_version = "CSB" #HCSB, NIV, NLT, ESV, etc.
  instant_page = true

  customCSS = ["example.css"]

  [params.favicon]
    sml = "/example16.png"
    med = "/example32.png"
    #lge = "example96.png"

  [params.banner]
    image = "img/banner.jpg"

#  [params.style]
#    googleFonts = ["Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

  [params.podcast]
    title = "Listen to Alpha Church"
    summary = "Alpha-Church sermons, talks, messagesâ€”podcasted."
    email = "test@example.com"
    copyright = "The files in the podcast are in the public domain."
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"
    iTunes = "https://itunes.apple.com/us/podcast/tgc-word-of-the-week/id1034013280"
    feed = "https://www.thegospelcoalition.org/podcasts/word-of-the-week/feed/?feed=podcast"
    spotify = "https://open.spotify.com/show/1iE3aJkf8fJ2FVTvJGFd4h"

  [params.map]
    service = "osm" #"osm" for OpenStreetMaps, "google" for Google Maps, or "mapbox" for Mapbox, see SETUP.md
    # For Open Street Map widgets
    latitude = "48.8530"
    longitude = "2.3498"
    zoom = "18"
    # If you want to use google maps you'll need an API Key from Google https://developers.google.com/maps/documentation/embed/get-api-key
    #service = "google"
    #api_key = "XXXXXXXX"
    #language = "fr" #Optional
    #region = "FR" #Optional

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify", "formspree" or "php"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (otherwise users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree form_id.
    #
    #If you use php, you need to host this site on a Server capable of running php.
    # Please edit the /static/contact_mail.php file from the exampleSite.
    service = "netlify" #or "formspree" or "php"
    confirm_page = "/contact_thanks" #only used by netlify
    # formspree_formid="" #only used by formspree


    [params.footer]
      copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)"
                  ]

    [[params.links]]
      service = "Twitter"
      icon = "fa-twitter"
      icon_pack = "fab"
      link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/"

    [[params.links]]
      service = "Podcast"
      icon = "fa-podcast"
      icon_pack = "fas"
      link = "/sermons/index.xml"

    [[params.links]]
      service = "Full RSS Feed"
      icon = "fa-rss"
      icon_pack = "fas"
      link = "/index.xml"
